import type { ExcalidrawElement } from "@crm/drawings";

type SymbolSeed = {
	name: string;
	elements: ExcalidrawElement[];
	widthFt: number;
	heightFt: number;
	serviceSymbolId: string | null;
};

export const BUILDING_SYMBOL_SEED: SymbolSeed[] = [
	{
		name: "Door with swing arc",
		widthFt: 3,
		heightFt: 3,
		serviceSymbolId: null,
		elements: [
			{
				id: "door-swing-el-37",
				type: "line",
				x: 5,
				y: 5,
				width: 4,
				height: 90,
				points: [
					[0, 0],
					[0, 90],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 279933,
				versionNonce: 283754,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "door-swing-el-38",
				type: "line",
				x: 5,
				y: 5,
				width: 90,
				height: 0,
				points: [
					[0, 0],
					[90, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 287575,
				versionNonce: 291396,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "door-swing-el-39",
				type: "line",
				x: 5,
				y: 5,
				width: 90,
				height: 90,
				points: [
					[0, 0],
					[26, 3],
					[50, 12],
					[68, 27],
					[80, 47],
					[85, 68],
					[86, 90],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 295217,
				versionNonce: 299038,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Double door",
		widthFt: 6,
		heightFt: 3,
		serviceSymbolId: null,
		elements: [
			{
				id: "double-door-el-40",
				type: "line",
				x: 5,
				y: 5,
				width: 4,
				height: 90,
				points: [
					[0, 0],
					[0, 90],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 302859,
				versionNonce: 306680,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "double-door-el-41",
				type: "line",
				x: 91,
				y: 5,
				width: 4,
				height: 90,
				points: [
					[0, 0],
					[0, 90],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 310501,
				versionNonce: 314322,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "double-door-el-42",
				type: "line",
				x: 5,
				y: 5,
				width: 45,
				height: 45,
				points: [
					[0, 0],
					[13, 2],
					[25, 6],
					[34, 14],
					[41, 25],
					[45, 45],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 318143,
				versionNonce: 321964,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "double-door-el-43",
				type: "line",
				x: 50,
				y: 5,
				width: 45,
				height: 45,
				points: [
					[45, 0],
					[32, 2],
					[20, 6],
					[11, 14],
					[4, 25],
					[0, 45],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 325785,
				versionNonce: 329606,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Window",
		widthFt: 3,
		heightFt: 1,
		serviceSymbolId: null,
		elements: [
			{
				id: "window-el-44",
				type: "rectangle",
				x: 5,
				y: 40,
				width: 90,
				height: 20,
				seed: 333427,
				versionNonce: 337248,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#d0ebff",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "window-el-45",
				type: "line",
				x: 50,
				y: 40,
				width: 0,
				height: 20,
				points: [
					[0, 0],
					[0, 20],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 341069,
				versionNonce: 344890,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Wall segment",
		widthFt: 8,
		heightFt: 1,
		serviceSymbolId: null,
		elements: [
			{
				id: "wall-segment-el-46",
				type: "line",
				x: 5,
				y: 35,
				width: 90,
				height: 0,
				points: [
					[0, 0],
					[90, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 348711,
				versionNonce: 352532,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "wall-segment-el-47",
				type: "line",
				x: 5,
				y: 65,
				width: 90,
				height: 0,
				points: [
					[0, 0],
					[90, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 356353,
				versionNonce: 360174,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Interior wall segment",
		widthFt: 8,
		heightFt: 0.5,
		serviceSymbolId: null,
		elements: [
			{
				id: "interior-wall-segment-el-48",
				type: "line",
				x: 5,
				y: 50,
				width: 90,
				height: 0,
				points: [
					[0, 0],
					[90, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 363995,
				versionNonce: 367816,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Stairs run",
		widthFt: 3,
		heightFt: 8,
		serviceSymbolId: null,
		elements: [
			{
				id: "stairs-run-el-49",
				type: "rectangle",
				x: 15,
				y: 5,
				width: 70,
				height: 90,
				seed: 371637,
				versionNonce: 375458,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "stairs-run-el-50",
				type: "line",
				x: 15,
				y: 20,
				width: 70,
				height: 0,
				points: [
					[0, 0],
					[70, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 379279,
				versionNonce: 383100,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "stairs-run-el-51",
				type: "line",
				x: 15,
				y: 35,
				width: 70,
				height: 0,
				points: [
					[0, 0],
					[70, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 386921,
				versionNonce: 390742,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "stairs-run-el-52",
				type: "line",
				x: 15,
				y: 50,
				width: 70,
				height: 0,
				points: [
					[0, 0],
					[70, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 394563,
				versionNonce: 398384,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "stairs-run-el-53",
				type: "line",
				x: 15,
				y: 65,
				width: 70,
				height: 0,
				points: [
					[0, 0],
					[70, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 402205,
				versionNonce: 406026,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "stairs-run-el-54",
				type: "line",
				x: 15,
				y: 80,
				width: 70,
				height: 0,
				points: [
					[0, 0],
					[70, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 409847,
				versionNonce: 413668,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "stairs-run-el-55",
				type: "arrow",
				x: 50,
				y: 15,
				width: 0,
				height: 60,
				points: [
					[0, 0],
					[0, 60],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: "triangle",
				seed: 417489,
				versionNonce: 421310,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Toilet",
		widthFt: 2,
		heightFt: 2.5,
		serviceSymbolId: null,
		elements: [
			{
				id: "toilet-el-56",
				type: "rectangle",
				x: 15,
				y: 10,
				width: 70,
				height: 30,
				seed: 425131,
				versionNonce: 428952,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "toilet-el-57",
				type: "ellipse",
				x: 20,
				y: 38,
				width: 60,
				height: 52,
				seed: 432773,
				versionNonce: 436594,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Sink",
		widthFt: 1.5,
		heightFt: 1.5,
		serviceSymbolId: null,
		elements: [
			{
				id: "sink-el-58",
				type: "rectangle",
				x: 10,
				y: 15,
				width: 80,
				height: 60,
				seed: 440415,
				versionNonce: 444236,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "sink-el-59",
				type: "ellipse",
				x: 25,
				y: 28,
				width: 50,
				height: 34,
				seed: 448057,
				versionNonce: 451878,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#d0ebff",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "sink-el-60",
				type: "ellipse",
				x: 45,
				y: 8,
				width: 10,
				height: 10,
				seed: 455699,
				versionNonce: 459520,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Bathtub",
		widthFt: 5,
		heightFt: 2.5,
		serviceSymbolId: null,
		elements: [
			{
				id: "bathtub-el-61",
				type: "rectangle",
				x: 5,
				y: 10,
				width: 90,
				height: 75,
				seed: 463341,
				versionNonce: 467162,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "bathtub-el-62",
				type: "rectangle",
				x: 15,
				y: 18,
				width: 70,
				height: 59,
				seed: 470983,
				versionNonce: 474804,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#d0ebff",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Kitchen range",
		widthFt: 2.5,
		heightFt: 2.5,
		serviceSymbolId: null,
		elements: [
			{
				id: "kitchen-range-el-63",
				type: "rectangle",
				x: 10,
				y: 10,
				width: 80,
				height: 80,
				seed: 478625,
				versionNonce: 482446,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "kitchen-range-el-64",
				type: "ellipse",
				x: 20,
				y: 20,
				width: 25,
				height: 25,
				seed: 486267,
				versionNonce: 490088,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "kitchen-range-el-65",
				type: "ellipse",
				x: 55,
				y: 20,
				width: 25,
				height: 25,
				seed: 493909,
				versionNonce: 497730,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "kitchen-range-el-66",
				type: "ellipse",
				x: 20,
				y: 55,
				width: 25,
				height: 25,
				seed: 501551,
				versionNonce: 505372,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "kitchen-range-el-67",
				type: "ellipse",
				x: 55,
				y: 55,
				width: 25,
				height: 25,
				seed: 509193,
				versionNonce: 513014,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Refrigerator",
		widthFt: 3,
		heightFt: 3,
		serviceSymbolId: null,
		elements: [
			{
				id: "refrigerator-el-68",
				type: "rectangle",
				x: 15,
				y: 5,
				width: 70,
				height: 90,
				seed: 516835,
				versionNonce: 520656,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "refrigerator-el-69",
				type: "line",
				x: 15,
				y: 40,
				width: 70,
				height: 0,
				points: [
					[0, 0],
					[70, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 524477,
				versionNonce: 528298,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "refrigerator-el-70",
				type: "rectangle",
				x: 55,
				y: 15,
				width: 6,
				height: 15,
				seed: 532119,
				versionNonce: 535940,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#1e1e1e",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Electrical outlet",
		widthFt: 0.5,
		heightFt: 0.5,
		serviceSymbolId: null,
		elements: [
			{
				id: "electrical-outlet-el-71",
				type: "ellipse",
				x: 15,
				y: 15,
				width: 70,
				height: 70,
				seed: 539761,
				versionNonce: 543582,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "electrical-outlet-el-72",
				type: "line",
				x: 40,
				y: 35,
				width: 0,
				height: 12,
				points: [
					[0, 0],
					[0, 12],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 547403,
				versionNonce: 551224,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "electrical-outlet-el-73",
				type: "line",
				x: 60,
				y: 35,
				width: 0,
				height: 12,
				points: [
					[0, 0],
					[0, 12],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 555045,
				versionNonce: 558866,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "electrical-outlet-el-74",
				type: "line",
				x: 35,
				y: 58,
				width: 30,
				height: 10,
				points: [
					[0, 0],
					[30, 10],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 562687,
				versionNonce: 566508,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Light switch",
		widthFt: 0.5,
		heightFt: 0.5,
		serviceSymbolId: null,
		elements: [
			{
				id: "light-switch-el-75",
				type: "ellipse",
				x: 15,
				y: 15,
				width: 70,
				height: 70,
				seed: 570329,
				versionNonce: 574150,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "light-switch-el-76",
				type: "line",
				x: 42,
				y: 30,
				width: 16,
				height: 40,
				points: [
					[0, 40],
					[16, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 577971,
				versionNonce: 581792,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Ceiling light",
		widthFt: 1,
		heightFt: 1,
		serviceSymbolId: null,
		elements: [
			{
				id: "ceiling-light-el-77",
				type: "ellipse",
				x: 15,
				y: 15,
				width: 70,
				height: 70,
				seed: 585613,
				versionNonce: 589434,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#fff3bf",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "ceiling-light-el-78",
				type: "line",
				x: 25,
				y: 25,
				width: 50,
				height: 50,
				points: [
					[0, 0],
					[50, 50],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 593255,
				versionNonce: 597076,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "ceiling-light-el-79",
				type: "line",
				x: 25,
				y: 75,
				width: 50,
				height: 50,
				points: [
					[0, 50],
					[50, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 600897,
				versionNonce: 604718,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
];
