import type { ExcalidrawElement } from "@crm/drawings";

type SymbolSeed = {
	name: string;
	elements: ExcalidrawElement[];
	widthFt: number;
	heightFt: number;
	serviceSymbolId: string | null;
};

export const LANDSCAPING_SYMBOL_SEED: SymbolSeed[] = [
	{
		name: "Deciduous tree",
		widthFt: 10,
		heightFt: 10,
		serviceSymbolId: null,
		elements: [
			{
				id: "deciduous-tree-el-1",
				type: "ellipse",
				x: 8,
				y: 5,
				width: 84,
				height: 80,
				seed: 4821,
				versionNonce: 8642,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#d3f9d8",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "deciduous-tree-el-2",
				type: "rectangle",
				x: 42,
				y: 78,
				width: 16,
				height: 20,
				seed: 12463,
				versionNonce: 16284,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#f1e4c8",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Evergreen tree",
		widthFt: 8,
		heightFt: 8,
		serviceSymbolId: null,
		elements: [
			{
				id: "evergreen-tree-el-3",
				type: "line",
				x: 15,
				y: 5,
				width: 70,
				height: 70,
				points: [
					[35, 0],
					[70, 70],
					[0, 70],
					[35, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 20105,
				versionNonce: 23926,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#b2f2bb",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "evergreen-tree-el-4",
				type: "rectangle",
				x: 42,
				y: 78,
				width: 16,
				height: 18,
				seed: 27747,
				versionNonce: 31568,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#f1e4c8",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Shrub",
		widthFt: 3,
		heightFt: 3,
		serviceSymbolId: null,
		elements: [
			{
				id: "shrub-el-5",
				type: "ellipse",
				x: 15,
				y: 25,
				width: 40,
				height: 40,
				seed: 35389,
				versionNonce: 39210,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#d3f9d8",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "shrub-el-6",
				type: "ellipse",
				x: 45,
				y: 25,
				width: 40,
				height: 40,
				seed: 43031,
				versionNonce: 46852,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#d3f9d8",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "shrub-el-7",
				type: "ellipse",
				x: 30,
				y: 10,
				width: 40,
				height: 40,
				seed: 50673,
				versionNonce: 54494,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#d3f9d8",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Hedge segment",
		widthFt: 4,
		heightFt: 1,
		serviceSymbolId: null,
		elements: [
			{
				id: "hedge-segment-el-8",
				type: "rectangle",
				x: 5,
				y: 40,
				width: 90,
				height: 25,
				seed: 58315,
				versionNonce: 62136,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#d3f9d8",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "hedge-segment-el-9",
				type: "line",
				x: 5,
				y: 40,
				width: 90,
				height: 10,
				points: [
					[0, 10],
					[15, 0],
					[30, 10],
					[45, 0],
					[60, 10],
					[75, 0],
					[90, 10],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 65957,
				versionNonce: 69778,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Flower bed patch",
		widthFt: 4,
		heightFt: 3,
		serviceSymbolId: null,
		elements: [
			{
				id: "flower-bed-el-10",
				type: "rectangle",
				x: 5,
				y: 5,
				width: 90,
				height: 90,
				seed: 73599,
				versionNonce: 77420,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#f1e4c8",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "flower-bed-el-11",
				type: "ellipse",
				x: 20,
				y: 20,
				width: 18,
				height: 18,
				seed: 81241,
				versionNonce: 85062,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#ffc9c9",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "flower-bed-el-12",
				type: "ellipse",
				x: 55,
				y: 30,
				width: 18,
				height: 18,
				seed: 88883,
				versionNonce: 92704,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#ffec99",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "flower-bed-el-13",
				type: "ellipse",
				x: 30,
				y: 60,
				width: 18,
				height: 18,
				seed: 96525,
				versionNonce: 100346,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#eebefa",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "flower-bed-el-14",
				type: "ellipse",
				x: 65,
				y: 65,
				width: 18,
				height: 18,
				seed: 104167,
				versionNonce: 107988,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#ffc9c9",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Boulder",
		widthFt: 2.5,
		heightFt: 2.5,
		serviceSymbolId: null,
		elements: [
			{
				id: "boulder-el-15",
				type: "line",
				x: 10,
				y: 15,
				width: 80,
				height: 70,
				points: [
					[15, 70],
					[0, 35],
					[25, 5],
					[60, 0],
					[80, 30],
					[65, 65],
					[30, 70],
					[15, 70],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 111809,
				versionNonce: 115630,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#e9ecef",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Paver square",
		widthFt: 1,
		heightFt: 1,
		serviceSymbolId: null,
		elements: [
			{
				id: "paver-square-el-16",
				type: "rectangle",
				x: 10,
				y: 10,
				width: 80,
				height: 80,
				seed: 119451,
				versionNonce: 123272,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#e9ecef",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Stepping stone",
		widthFt: 1.5,
		heightFt: 1.5,
		serviceSymbolId: null,
		elements: [
			{
				id: "stepping-stone-el-17",
				type: "ellipse",
				x: 10,
				y: 15,
				width: 80,
				height: 70,
				seed: 127093,
				versionNonce: 130914,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#e9ecef",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Sprinkler head",
		widthFt: 0.5,
		heightFt: 0.5,
		serviceSymbolId: null,
		elements: [
			{
				id: "sprinkler-head-el-18",
				type: "ellipse",
				x: 35,
				y: 35,
				width: 30,
				height: 30,
				seed: 134735,
				versionNonce: 138556,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "sprinkler-head-el-19",
				type: "line",
				x: 50,
				y: 5,
				width: 0,
				height: 20,
				points: [
					[0, 0],
					[0, 20],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 142377,
				versionNonce: 146198,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "sprinkler-head-el-20",
				type: "line",
				x: 50,
				y: 75,
				width: 0,
				height: 20,
				points: [
					[0, 0],
					[0, 20],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 150019,
				versionNonce: 153840,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "sprinkler-head-el-21",
				type: "line",
				x: 5,
				y: 50,
				width: 20,
				height: 0,
				points: [
					[0, 0],
					[20, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 157661,
				versionNonce: 161482,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "sprinkler-head-el-22",
				type: "line",
				x: 75,
				y: 50,
				width: 20,
				height: 0,
				points: [
					[0, 0],
					[20, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 165303,
				versionNonce: 169124,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Drip emitter",
		widthFt: 0.5,
		heightFt: 0.5,
		serviceSymbolId: null,
		elements: [
			{
				id: "drip-emitter-el-23",
				type: "ellipse",
				x: 35,
				y: 35,
				width: 30,
				height: 30,
				seed: 172945,
				versionNonce: 176766,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#d0ebff",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "drip-emitter-el-24",
				type: "line",
				x: 65,
				y: 50,
				width: 25,
				height: 0,
				points: [
					[0, 0],
					[25, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 180587,
				versionNonce: 184408,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Landscape light",
		widthFt: 1,
		heightFt: 1,
		serviceSymbolId: null,
		elements: [
			{
				id: "landscape-light-el-25",
				type: "line",
				x: 45,
				y: 40,
				width: 10,
				height: 50,
				points: [
					[5, 0],
					[5, 50],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 188229,
				versionNonce: 192050,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "landscape-light-el-26",
				type: "ellipse",
				x: 30,
				y: 10,
				width: 40,
				height: 30,
				seed: 195871,
				versionNonce: 199692,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#fff3bf",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "landscape-light-el-27",
				type: "rectangle",
				x: 35,
				y: 88,
				width: 30,
				height: 8,
				seed: 203513,
				versionNonce: 207334,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#e9ecef",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Fence post",
		widthFt: 0.5,
		heightFt: 0.5,
		serviceSymbolId: null,
		elements: [
			{
				id: "fence-post-el-28",
				type: "rectangle",
				x: 35,
				y: 20,
				width: 30,
				height: 70,
				seed: 211155,
				versionNonce: 214976,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#f1e4c8",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "fence-post-el-29",
				type: "line",
				x: 35,
				y: 10,
				width: 30,
				height: 10,
				points: [
					[0, 10],
					[15, 0],
					[30, 10],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 218797,
				versionNonce: 222618,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#f1e4c8",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Gate",
		widthFt: 4,
		heightFt: 1,
		serviceSymbolId: null,
		elements: [
			{
				id: "gate-el-30",
				type: "rectangle",
				x: 5,
				y: 30,
				width: 12,
				height: 60,
				seed: 226439,
				versionNonce: 230260,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#f1e4c8",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "gate-el-31",
				type: "rectangle",
				x: 83,
				y: 30,
				width: 12,
				height: 60,
				seed: 234081,
				versionNonce: 237902,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#f1e4c8",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "gate-el-32",
				type: "rectangle",
				x: 17,
				y: 40,
				width: 66,
				height: 40,
				seed: 241723,
				versionNonce: 245544,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "gate-el-33",
				type: "line",
				x: 17,
				y: 40,
				width: 66,
				height: 40,
				points: [
					[0, 0],
					[66, 40],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 249365,
				versionNonce: 253186,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "transparent",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
	{
		name: "Fire pit",
		widthFt: 4,
		heightFt: 4,
		serviceSymbolId: null,
		elements: [
			{
				id: "fire-pit-el-34",
				type: "ellipse",
				x: 5,
				y: 5,
				width: 90,
				height: 90,
				seed: 257007,
				versionNonce: 260828,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#e9ecef",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "fire-pit-el-35",
				type: "ellipse",
				x: 25,
				y: 25,
				width: 50,
				height: 50,
				seed: 264649,
				versionNonce: 268470,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#ffd8a8",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
			{
				id: "fire-pit-el-36",
				type: "line",
				x: 42,
				y: 35,
				width: 16,
				height: 30,
				points: [
					[8, 0],
					[16, 30],
					[0, 30],
					[8, 0],
				],
				lastCommittedPoint: null,
				startBinding: null,
				endBinding: null,
				startArrowhead: null,
				endArrowhead: null,
				seed: 272291,
				versionNonce: 276112,
				angle: 0,
				strokeColor: "#1e1e1e",
				backgroundColor: "#ff922b",
				fillStyle: "solid",
				strokeWidth: 2,
				strokeStyle: "solid",
				roughness: 1,
				opacity: 100,
				groupIds: [],
				frameId: null,
				boundElements: null,
				updated: 1793000000000,
				link: null,
				locked: false,
				isDeleted: false,
				version: 1,
			},
		],
	},
];
